### ISSUE TITLE
リソース設計

### ISSUE THREAD

**Issue by OdenTakashi** [OdenTakashi/SmartLottery#18]
## メイン部分
|HTTPメソッド|URL|何をやるかの説明|
| --- | --- | --- |
| GET | /welcome | ウェルカムページを表示する |
| GET | / | 抽選会一覧を表示する |
| GET | /lotteries/{lottery_uuid} | 抽選会詳細画面を表示する |
| GET | /lotteries/new | 抽選会作成画面を表示する |
| POST | /lotteries  | 抽選会を作成する |
| GET | /lotteries/{lottery_uuid}/edit | 抽選会編集画面を表示する |
| PATCH | /lotteries/{lottery_uuid} | 抽選会を編集する |
| DELETE | /lotteries/{lottery_uuid} | 抽選会を削除する |
| GET | /lotteries/{lottery_uuid}/entries/new | 応募フォームを表示する|
| POST | /lotteries/{lottery_uuid}/entries| 応募をする|
| GET | /lotteries/{lottery_uuid}/entries/completed | 応募完了画面を表示する|
| GET | /lotteries/{lottery_uuid}/entries/closed| 応募終了画面表示する|
| GET | /terms | 利用規約を表示する |
| GET | /privacy | 利用規約を表示する |

## ユーザー認証、編集部分
deviseのdevise_for :usersで作成されるURLを使用する予定です。

## 懸念点
以下の1点が自信が持てていないため、アドバイスいただきたいです🙏

- 応募終了画面、応募完了画面のURLについて

その他にも不十分な箇所がありましたらアドバイスいただきたいです。

#### 応募終了画面、応募完了画面の表示ついて

抽選会が行われた日付よりも後に、応募フォームにアクセスを行うと以下のように応募は終了しましたというページを表示します。

![image](https://github.com/OdenTakashi/SmartLottery/assets/81839214/d11f89a0-2330-4b68-9d9c-44ba90b95882)

また、応募完了画面は応募フォームで応募が完了した後に以下のようなページにリダイレクトします。

![image](https://github.com/OdenTakashi/SmartLottery/assets/81839214/7f2ebe8c-86a0-40e0-bfb6-4d913ba9217d)

***

|HTTPメソッド|URL|何をやるかの説明|
| --- | --- | --- |
| GET | /lotteries/{lottery_uuid}/entries/closed| 応募終了画面表示する|
| GET | /lotteries/{lottery_uuid}/entries/completed  | 応募完了画面を表示する|

応募終了画面表示する、応募完了画面表示する際のURLを上のように考えていますが、あまり自信が持てていません。
自信が持てない理由としては、URLはリソースを表すものと考えているので今回のようにリソースの状態を表すのはアンチパターンなのではないかと考えたためです。

**Comment by OdenTakashi** [comment]
📝
- `/lotteries/{lottery_id}/entry/{uuid}`
- 応募者ではなく応募(entry)
- 当選はentryの中に賞品のデータを持っていることで当選したかどうかを判断する。
    - 別のテーブルは作らなくても良い

**Comment by maedana** [comment]
> 応募終了画面表示する、応募完了画面表示する際のURLを上のように考えていますが、あまり自信が持てていません。
自信が持てない理由としては、URLはリソースを表すものと考えているので今回のようにリソースの状態を表すのはアンチパターンなのではないかと考えたためです。

終了については、単に`/lotteries/{lottery_uuid}`が終了しているか否かというだけで、専用URL用意する必要なく上記URLで画面を切り分ければいいだけなんじゃないですかね。終了してないときに終了画面にアクセス出来る必要がないわけですし、URL分ける必要性がないかなと思いました。

応募完了については特に違和感ないです。`/lotteries/{lottery_uuid}/edit`のような画面だってRESTで対応するものがないので割り当ててるだけですしねー。同じことかと。強いて言うなら`/lotteries/{lottery_uuid}/entries/new`ですでに応募されているときは応募完了画面を表示する、でもいいかと思いますよ。

**Comment by OdenTakashi** [comment]
@maedana 
ご確認いただきありがとうございます🙏

> 終了については、単に/lotteries/{lottery_uuid}が終了しているか否かというだけで、専用URL用意する必要なく上記URLで画面を切り分ければいいだけなんじゃないですかね。終了してないときに終了画面にアクセス出来る必要がないわけですし、URL分ける必要性がないかなと思いました。
応募完了については特に違和感ないです。/lotteries/{lottery_uuid}/editのような画面だってRESTで対応するものがないので割り当ててるだけですしねー。同じことかと。強いて言うなら/lotteries/{lottery_uuid}/entries/newですでに応募されているときは応募完了画面を表示する、でもいいかと思いますよ。

アドバイスいただきありがとうございます。
maedanaさんのアドバイスを参考に以下のように、`/lotteries/{lottery_uuid}/entries/new`内の表示を場合ごとに変えようと考えたのですが、いかがでしょうか?

`/lotteries/{lottery_uuid}/entries/new`(応募フォーム)にアクセス

抽選会にまだ応募していないかつ、抽選会が開催している場合
-> 応募フォームを表示

すでに抽選会に応募している場合
-> 応募完了画面の表示

抽選会にまだ応募していないかつ、抽選会が終了している場合
->  抽選会終了画面の表示

**Comment by OdenTakashi** [comment]
@maedana 
> ところで、当選した後の流れってどういう想定なんでしょう? ペーパープロトを拝見すると本など想定していると思うのですけど、住所等の個人情報のやり取りをすることになるのかなーと思いましたが。

フィヨルドブートキャンプ内で使用するという文脈だと自分は認識しているため、当選後の流れとしては以下のように考えています。

1. 当選者にメールが届く(メールの内容は「相談部屋から個人情報の教えてください」というような趣旨)
2. 相談部屋などで個人情報のやりとりを行う
3. 実際に発送などを行う

しかし今回のサービスはフィヨルドブートキャンプが用意した案になります。
そのため、上記の認識がズレていたら良くないので再度machidaさんに確認を取りたいと思います。

確認が完了次第、再度が連絡差し上げますので少々お待ちください。🙌

**Comment by OdenTakashi** [comment]
@maedana 
machidaさんに確認を取りましたので、ご連絡いたします。

> ところで、当選した後の流れってどういう想定なんでしょう? ペーパープロトを拝見すると本など想定していると思うのですけど、住所等の個人情報のやり取りをすることになるのかなーと思いましたが。

当選後の個人情報のやりとりはメールで行います。
アプリ側ではどこの誰に発送するのか、どうやって発送するのかを担う機能は持ちません。

> システムでサポートするのも大変だし、抵抗ない人はメールで住所情報などやり取りしてね。それが嫌なら何らかの匿名発送でやり取りしてね、とかになるのかもですね。

こちらはmaedanaさんのアドバイスを参考に当選メール作成の欄に例として以下のように載せようと思います。
具体的な匿名発送方法はこれから調べる予定です。

![image](https://github.com/OdenTakashi/SmartLottery/assets/81839214/66e386ab-529e-4b05-bb95-2a7dd1512bd7)

**Comment by maedana** [comment]
なるほどー、ブートキャンプ内利用想定だったのですね。把握しきれておらずすみません。
であればコメントされている内容でいいと思います :+1: 

卒業生等がいらなくなった参考書等を現役生にプレゼントするなり、何かのイベントの景品等で運営からプレゼントしたりなどってことかなーと思いました。

**Comment by OdenTakashi** [comment]
@maedana 

> ブートキャンプ内利用想定だったのですね。把握しきれておらずすみません。

申し訳ありません💦🙇‍♂️
こちら伝えそびれてしまった点が一点ありました。

https://github.com/OdenTakashi/SmartLottery/issues/18#issuecomment-1649211676
こちらで自分はFBC内利用想定だと認識していたのですが、machidaさんに確認をとったところFBC外でも利用できるようにするとのことでした。

**Comment by OdenTakashi** [comment]
確認いただいたのでcloseします。
