### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by OdenTakashi** [OdenTakashi/SmartLottery#19]
```mermaid
erDiagram
    Users ||--o{ Lotteries: ""
    Lotteries ||--|{ Prizes: ""
    Lotteries ||--o{ Entries: ""
    Prizes ||--o{ Entries: ""

    Users {
        integer id PK "null:false"
        string email "null:false"
        string encrypted_password "null:false"
        string reset_password_token
        datetime reset_password_sent_at
        datetime remember_created_at
        string confirmation_token
        datetime confirmed_at
        datetime confirmation_sent_at
        string unconfirmed_email
        timestamp created_at "null:false"
        timestamp updated_at "null:false"
    }

    Lotteries {
        uuid id PK "null:false"
        integer user_id FK "null:false"
        boolean name_field_enabled "null:false"
        boolean note_field_enabled "null:false"
        date deadline "null:false"
        timestamp created_at "null:false"
        timestamp updated_at "null:false"
    }

    Prizes {
        integer id PK "null:false"
        uuid lottery_id FK "null:false"
        string name "null:false"
        integer winners_count "null:false"
        string winning_email_subject "null:false"
        string winning_email_body "null:false"
        timestamp created_at "null:false"
        timestamp updated_at "null:false"
    }

    Entries {
        integer id PK "null:false"
        uuid lottery_id FK "null:false"
        integer prize_id FK
        string email "null:false"
        string name
        string note
        timestamp created_at "null:false"
        timestamp updated_at "null:false"
    }
```

## Users
| 論理名称 | 物理名称 | データ型 | PK | FK | UQ | NN | 
| --- | --- | --- | --- | --- | --- | --- |
| id | id | integer | O |  | O | O |
| メールアドレス | email | string |  |  | O | O |
| パスワード | encrypted_password | string |  |  |  | O |
| パスワードリセット用のトークン | reset_password_token | string |  |  |  |  |
| パスワードリセットメールの送信日時 | reset_password_sent_at | datetime |  |  |  |  |
| 「記憶する」オプションの有効化日時 | remember_created_at | datetime |  |  |  |  |
| メール確認のためのトークン | confirmation_token | string |  |  |  |  |
| メール確認完了日時 | confirmed_at | datetime |  |  |  |  |
| 確認メールが送信された日時 | confirmation_sent_at | datetime |  |  |  |  |
| 未確認のメールアドレス | unconfirmed_email | string |  |  |  |  |
| 作成日 | created_at | timestamp |  |  |  | O |
| 更新日 | updated_at | timestamp |  |  |  | O |

## Lotteries
| 論理名称 | 物理名称 | データ型 | PK | FK | UQ | NN | 
| --- | --- | --- | --- | --- | --- | --- |
| id | id | uuid | O |  | O | O |
| user_id | user_id | integer |  | O | O | O |
| 応募フォームに名前を必要とするか | name_field_enabled | boolean |  |  |  | O |
| 応募フォームに備考を必要とするか | note_field_enabled | boolean |  |  |  | O |
|締め切り日 | deadline | date |  |  |  | O |
| 作成日 | created_at | timestamp |  |  |  | O |
| 更新日 | updated_at | timestamp |  |  |  | O |

## Prizes
| 論理名称 | 物理名称 | データ型 | PK | FK | UQ | NN | 
| --- | --- | --- | --- | --- | --- | --- |
| id | id | integer | O |  | O | O |
| lottery_id | lottery_id | uuid |  | O | O | O |
| 賞品名 | name | string |  |  |  | O |
| 当選メールのタイトル | winning_email_subject |  |  |  |  | O |
| 当選メールの内容 | winning_email_body |  |  |  |  | O |
| 当選者数 | winners_count | timestamp |  |  |  | O |
| 作成日 | created_at | timestamp |  |  |  | O |
| 更新日 | updated_at | timestamp |  |  |  | O |

## Entries
| 論理名称 | 物理名称 | データ型 | PK | FK | UQ | NN | 
| --- | --- | --- | --- | --- | --- | --- |
| id | id | integer | O |  | O | O |
| lottery_id | lottery_id | uuid |  | O | O | O |
| prize_id | prize_id | integer |  | O |  |  |
| メールアドレス | email | string |  |  |  | O |
| 応募者の名前 | name | string |  |  |  |  |
| 備考 | note | string |  |  |  |  |
| 作成日 | created_at | timestamp |  |  |  | O |
| 更新日 | updated_at | timestamp |  |  |  | O |

## 備考
- 一つの抽選会には複数の賞品を持つことができますが、仕様として応募者はどちらかの商品に応募するということはできません。
- 当選したかどうかを表すために`Entries`テーブルに`prize_id`を持たせています。当選した場合、賞品番号が入る形になります。

**Comment by maedana** [comment]
- Usersですが、devise依存だとするともっと色々カラム入ってくると思いますよー。
- Lotteriesのis_enabled_name_field, is_enabled_note_fieldはちょっと冗長なのでは。`name_field_enabled`くらいでいいんじゃないですかね
- Lotteriesのdeadlineがtimestampですが日付だけでよかったりしないのですか? もし日付だけでいいなら`date`型でいいかなと
- Prizesですが、景品名だけでいいんですかね? 景品の説明とか、景品画像とか不要ですか? 一旦一通り作ってから余力があれば機能拡張とかでもいい部分だとは思いますが。

**Comment by OdenTakashi** [comment]
@maedana 
ご確認いただきありがとうございます🙏

> Usersですが、devise依存だとするともっと色々カラム入ってくると思いますよー。

すみません💦この点見落としていましたので、修正しました。

> Lotteriesのis_enabled_name_field, is_enabled_note_fieldはちょっと冗長なのでは。name_field_enabledくらいでいいんじゃないですかね

なるほどです。booleanが入るので`is~`としていたのですが、確かに長いなと思ったのでご提案いただいた`name_field_enabled`に加えて`is_enabled_note_field`->`note_field_enabled`に修正しました。

> Lotteriesのdeadlineがtimestampですが日付だけでよかったりしないのですか? もし日付だけでいいならdate型でいいかなと
> Prizesですが、景品名だけでいいんですかね? 景品の説明とか、景品画像とか不要ですか? 一旦一通り作ってから余力があれば機能拡張とかでもいい部分だとは思いますが。

この2点についてなのですが、一度machidaさんに確認を取りたいので少しお時間をいただきたいです。
確認が完了次第、再度ご連絡いたします🙏

**Comment by OdenTakashi** [comment]
@maedana 
> Lotteriesのdeadlineがtimestampですが日付だけでよかったりしないのですか? もし日付だけでいいならdate型でいいかなと

こちら日時である必要はないとのことでしたので、date型を使用したいと思います。

> Prizesですが、景品名だけでいいんですかね? 景品の説明とか、景品画像とか不要ですか? 一旦一通り作ってから余力があれば機能拡張とかでもいい部分だとは思いますが。

景品の説明や画像はアプリの外側のお知らせに載せるため必要ないとのことです。

**Comment by maedana** [comment]
こちらもコメント頂いた内容でOKです

**Comment by OdenTakashi** [comment]
確認いただいたのでcloseします。
